name: Release Fork

on:
  push:

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            "$GITHUB_REF_NAME" \
            --prerelease \
            --notes "Directus $GITHUB_REF_NAME"

